import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: "5mb" }));

  // Initialize Gemini API
  const ai = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      }
    }
  });

  // Reusable helper with automatic model fallback to avoid 503/high-demand failures
  const generateContentWithFallback = async (contents: string, config: any) => {
    const models = ["gemini-3.5-flash", "gemini-2.5-flash", "gemini-1.5-flash"];
    let lastError: any = null;

    for (const model of models) {
      try {
        const response = await ai.models.generateContent({
          model,
          contents,
          config,
        });
        return response;
      } catch (err: any) {
        lastError = err;
        console.warn(`Model ${model} failed. Error:`, err?.message || err);
      }
    }
    throw lastError || new Error("All AI models in fallback registry are currently unavailable.");
  };

  // API Route for Detection
  app.post("/api/analyze", async (req, res) => {
    try {
      const { code, languageHint } = req.body;
      if (!code || code.trim().length < 3) {
        return res.status(400).json({ error: "Code must be at least 3 characters long." });
      }

      const systemInstruction = `You are an expert code analyst. Analyze the code provided and determine if it was written by a human developer or generated by an AI tool (like ChatGPT, Copilot, or Gemini). 
Respond ONLY in valid JSON with no extra text, no markdown, no code fences. Use exactly this structure:
{
  "verdict": "AI_GENERATED" or "HUMAN_WRITTEN",
  "confidence": <integer 0 to 100>,
  "language": "<detected language name>",
  "reasoning": "<2 to 3 sentences explaining why>",
  "indicators": ["<pattern 1>", "<pattern 2>", "<pattern 3>"]
}`;

      const userPrompt = `Analyze this code:
${code}

Language hint: ${languageHint || "Auto Detect"}`;

      const response = await generateContentWithFallback(userPrompt, {
        systemInstruction,
        responseMimeType: "application/json",
        temperature: 0.1,
      });

      const responseText = response.text;
      if (!responseText) {
        throw new Error("Empty response from Gemini.");
      }

      // Parse JSON directly and send back
      const data = JSON.parse(responseText.trim());
      res.json(data);
    } catch (error: any) {
      console.error("Analysis Error:", error);
      res.status(500).json({ error: error.message || "An error occurred during analysis." });
    }
  });

  // API Route for Humanization
  app.post("/api/humanize", async (req, res) => {
    try {
      const { code } = req.body;
      if (!code) {
        return res.status(400).json({ error: "No code provided for humanization." });
      }

      const systemInstruction = `You are a senior software developer with 10 years of experience. Rewrite the following AI-generated code so it looks like it was written by a real human developer. Apply all of these naturally:
- Use varied, casual variable names and abbreviations a human would actually choose
- Add inline comments only where a developer would genuinely add a note
- Introduce minor inconsistencies in spacing or style that reflect human habit
- Avoid overly perfect structure, uniform naming, or excessive documentation
- Use pragmatic shortcuts familiar to experienced developers in that language
- Remove any over-engineered boilerplate or perfectly symmetrical patterns
Return ONLY the rewritten code. No explanation. No markdown. No code fences. Raw code only.`;

      const response = await generateContentWithFallback(`Rewrite this AI-generated code in a human style:\n${code}`, {
        systemInstruction,
        temperature: 0.75,
      });

      let responseText = response.text || "";
      
      // Clean up markdown code blocks if the model wrapped it in code fences
      responseText = responseText.trim();
      if (responseText.startsWith("```")) {
        const lines = responseText.split("\n");
        if (lines[0].startsWith("```")) {
          lines.shift();
        }
        if (lines.length > 0 && lines[lines.length - 1].trim() === "```") {
          lines.pop();
        }
        responseText = lines.join("\n");
      }

      res.json({ humanizedCode: responseText });
    } catch (error: any) {
      console.error("Humanization Error:", error);
      res.status(500).json({ error: error.message || "An error occurred during humanization." });
    }
  });

  // Serve static files or setup Vite in development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
